name: VEX Build
  # You may pin to the exact commit or the version.
  # uses: schineaj23/vex-build@51522ea2fe2cc558e56c3e764f2ae6a88c0bf70e
  uses: schineaj23/vex-build@v1.0
  with:
    # Path to makefile
    path: # optional, default is .
